version: '3'

services:
  parent:
    image: server_p1
    build:
      context: .
      dockerfile: Dockerfiles/server_p1
    environment:
      C1: http://child1:8080/
      C2: http://child2:8080/
    ports:
      - "8080:8080"

  child1:
    image: server_c1
    build:
      context: .
      dockerfile: Dockerfiles/server_c1
    ports:
      - "8081:8080"

  child2:
    image: server_c2
    build:
      context: .
      dockerfile: Dockerfiles/server_c2
    ports:
      - "8082:8080"

  state:
    image: server_state
    build:
      context: .
      dockerfile: Dockerfiles/server_state
    environment:
      - STATEFILEPATH=/volume/state.txt
    volumes:
      - ./volume:/volume
    ports:
      - "8083:8080"
