Parameters: 
  TaskCount: 
    Type: String

Resources:
  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Sub "arn:aws:ecs:ap-northeast-1:${AWS::AccountId}:cluster/cluster01"
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DesiredCount: !Sub ${TaskCount}
      LaunchType: "FARGATE"
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: "ENABLED"
          SecurityGroups:
            - "sg-00c8234ac2da03dff"
          Subnets:
            - subnet-74f0f800
      PlatformVersion: "LATEST"
      SchedulingStrategy: "REPLICA"
      # ServiceName: "service04"
      TaskDefinition: !Sub "arn:aws:ecs:ap-northeast-1:${AWS::AccountId}:task-definition/task01:10"
