version: 0.2
batch:
  fast-fail: true

phases:
  build:
    on-failure: CONTINUE
    commands:
      - ls
      - date | tee -a envnote.txt
      - echo "============================================================" | tee -a envnote.txt
      - pwd | tee -a envnote.txt
      - echo "============================================================" | tee -a envnote.txt
      - env | tee -a envnote.txt
      - echo "============================================================" | tee -a envnote.txt
      - ls -l | tee -a envnote.txt
      - echo "============================================================" | tee -a envnote.txt
      - go version
      - bash ./update-version.sh
      - cat version.go
      - go build container-test.go version.go
      - docker image build -t container-test .
      - docker tag ${ECRRepositoryUri}:v2
      - docker push ${ECRRepositoryUri}:v2
artifacts:
  files:
    - envnote.txt
